ImouRentACar/Models/State.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ImouRentACar.Models
{
    public class State : Transport
    {
        #region Model Data
        
        public int StateId { get; set; }

        [Required(ErrorMessage="Name field is required!!!")]
        public string Name { get; set; }

        #endregion
    }
}

ImouRentACar/Controllers/StateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ImouRentACar.Data;
using ImouRentACar.Models;
using ImouRentACar.Models.Enums;
using ImouRentACar.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace ImouRentACar.Controllers
{
    public class StateController : Controller
    {
        private readonly ApplicationDbContext _database;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private ISession _session => _httpContextAccessor.HttpContext.Session;

        #region Constructor

        public StateController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _database = context;
            _httpContextAccessor = httpContextAccessor;
        }

        #endregion

        #region Index

        [HttpGet]
        [Route("state/index")]
        public async Task<IActionResult> Index()
        {
            var userid = _session.GetInt32("imouloggedinuserid");
            var _user = await _database.ApplicationUsers.FindAsync(userid);
            ViewData["loggedinuserfullname"] = _user.DisplayName;

            var roleid = _user.RoleId;

            var role = _database.Roles.Find(roleid);

            ViewData["userrole"] = role.Name;

            if (role.CanManageLocation == false && role.CanDoEverything == false)
            {
                return RedirectToAction("Index", "Error");
            }

            ViewData["canmangecars"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageCars == true && r.RoleId == roleid);
            ViewData["canmangecustomers"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageCustomers == true && r.RoleId == roleid);
            ViewData["canmangelandingdetails"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageLandingDetails == true && r.RoleId == roleid);
            ViewData["canmangeprices"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManagePrices == true && r.RoleId == roleid);
            ViewData["canmangeenquries"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageEnquires == true && r.RoleId == roleid);
            ViewData["canmangebookings"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageBookings == true && r.RoleId == roleid);
            ViewData["canmangelocation"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageLocation == true && r.RoleId == roleid);
            ViewData["canmangedrivers"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageDrivers == true && r.RoleId == roleid);
            ViewData["canmangepassengersinformation"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManagePassengersInformation == true && r.RoleId == roleid);
            ViewData["candoeverything"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanDoEverything == true && r.RoleId == roleid);
            ViewData["canmanageapplicationusers"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageApplicationUsers == true && r.RoleId == roleid);


            var _state = await _database.States.ToListAsync();
            return View(_state);
        }

        #endregion

        #region Create

        [HttpGet]
        public IActionResult Create()
        {
            var _state = new State();
            return PartialView("Create", _state);
        }

        [HttpPost]
        [SessionExpireFilterAttribute]
        public async Task<IActionResult> Create(State state)
        {
            if (ModelState.IsValid)
            {
                var allStates = await _database.States.ToListAsync();
                if (allStates.Any(b => b.Name == state.Name))
                {
                    TempData["state"] = "You cannot add " + state.Name + " as a state because it already exist!!!";
                    TempData["notificationType"] = NotificationType.Error.ToString();
                    return View("Index");
                }

                var _state = new State()
                {
                    Name = state.Name,
                    CreatedBy = Convert.ToInt32(_session.GetInt32("imouloggedinuserid")),
                    DateCreated = DateTime.Now,
                    LastModifiedBy = Convert.ToInt32(_session.GetInt32("imouloggedinuserid")),
                    DateLastModified = DateTime.Now
                };

                await _database.States.AddAsync(_state);
                await _database.SaveChangesAsync();

                TempData["state"] = "You have successfully added " + state.Name + " State.";
                TempData["notificationType"] = NotificationType.Success.ToString();

                return Json(new { success = true });
            }
            return View("Index");
        }

        #endregion

        #region Edit

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return RedirectToAction("Index", "Error");
            }

            var _state = await _database.States.SingleOrDefaultAsync(s => s.StateId == id);

            if (_state == null)
            {
                return RedirectToAction("Index", "Error");
            }

            return PartialView("Edit", _state);
        }

        [HttpPost]
        [SessionExpireFilterAttribute]
        public async Task<IActionResult> Edit(int id, State state)
        {
            if(id != state.StateId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    state.LastModifiedBy = Convert.ToInt32(_session.GetInt32("imouloggedinuserid"));
                    state.DateLastModified = DateTime.Now;

                    _database.Update(state);
                    await _database.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StateExists(state.StateId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                TempData["state"] = "You have successfully modified " + state.Name + " State.";
                TempData["notificationType"] = NotificationType.Success.ToString();

                return Json(new { success = true });
            }
            return View(state);
        }

        #endregion

        #region Details

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            var userObject = _session.GetString("imouloggedinuser");
            var _user = JsonConvert.DeserializeObject<ApplicationUser>(userObject);
            var roleid = _user.RoleId;
            var role = _database.Roles.Find(roleid);
            ViewData["rolename"] = role.Name;
            if (role.CanManageLocation == false && role.CanDoEverything == false)
            {
                return RedirectToAction("Index", "Error");
            }

            if (id == null)
            {
                return RedirectToAction("Index", "Error");
            }

            var _state = await _database.States.SingleOrDefaultAsync(c => c.StateId == id);

            if (_state == null)
            {
                return RedirectToAction("Index", "Error");
            }

            
            var creatorid = _state.CreatedBy;
            var creator = await _database.ApplicationUsers.FindAsync(creatorid);
            ViewData["creatorby"] = creator.DisplayName;

            var modifierid = _state.LastModifiedBy;
            var modifier = await _database.ApplicationUsers.FindAsync(modifierid);
            ViewData["modifiedby"] = modifier.DisplayName;
            
            return PartialView(_state);
        }

        #endregion

        #region Delete

        [HttpGet]
        [SessionExpireFilter]
        public async Task<IActionResult> Delete(int? id)
        {
            var userid = _session.GetInt32("imouloggedinuserid");
            var _user = await _database.ApplicationUsers.FindAsync(userid);
            var roleid = _user.RoleId;
            var role = _database.Roles.Find(roleid);

            if (role.CanManageLocation == false && role.CanDoEverything == false)
            {
                return RedirectToAction("Index", "Error");
            }

            if (id == null)
            {
                return RedirectToAction("Index", "Error");
            }

            var _state = await _database.States.SingleOrDefaultAsync(s => s.StateId == id);

            if(_state == null)
            {
                return RedirectToAction("Index", "Error");
            }

            return PartialView("Delete", _state);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var state = await _database.States.SingleOrDefaultAsync(s => s.StateId == id);

            if(state != null)
            {
                _database.States.Remove(state);
                await _database.SaveChangesAsync();

                TempData["state"] = "You have successfully deleted " + state.Name + " State.";
                TempData["notificationType"] = NotificationType.Success.ToString();

                return Json(new { success = true });
            }
            return View("Index");
        }

        #endregion

        #region View Lgas

        [HttpGet]
        public async Task<IActionResult> ViewLgas(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Error");
            }

            var stateLgas = await _database.Lgas.Where(sl => sl.StateId == id).ToListAsync();

            if(stateLgas == null)
            {

ImouRentACar/Views/State/Create.cshtml
@model ImouRentACar.Models.State

@{
    ViewData["Title"] = "Create";
    Layout = null;
}

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3> <strong> ADD A STATE </strong> </h3>
</div>

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <!--MODAL BODY-->
    <div class="modal-body">
        <div class="form-horizontal">
            <div class="row">
                <div class="col-md-12">
                    <label>NAME</label>
                    <input asp-for="Name" class="form-control " placeholder="Name" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
        </div>
    </div>

    <!--MODAL FOOTER-->
    <div class="modal-footer">
        <div class="row pull-right">
            <div class="col-md-12">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a class="btn btn-danger" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ImouRentACar/Views/State/Delete.cshtml
@model ImouRentACar.Models.State

@{
    ViewData["Title"] = "Delete";
    Layout = null;
}

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3> <strong> DELETE STATE </strong> </h3>
</div>


<!--MODAL BODY-->
<div class="modal-body">
    <h3 class="text-center"> Are you sure you want to delete @Html.DisplayFor(model => model.Name) State?</h3>
</div>
<form asp-action="Delete">
    <input type="hidden" asp-for="StateId" />

    <!--MODAL FOOTER-->
    <div class="modal-footer">
        <div class="row pull-right">
            <div class="col-md-12">
                <input type="submit" value="Yes" class="btn btn-primary" />
                <a class="btn btn-danger" data-dismiss="modal">No</a>
            </div>
        </div>
    </div>
</form>

ImouRentACar/Views/State/Details.cshtml
@model ImouRentACar.Models.State

    @{
        ViewData["Title"] = "Detials";
        Layout = null;
    }

    <!--MODAL HEADER-->
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3> <strong> STATE DETAILS </strong> </h3>
    </div>

     <!--MODAL BODY-->
        <div class="modal-body">
            <div class="row">
                <div class="col-md-4">
                    <dt style="text-transform:capitalize">
                        NAME
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                </div>
            </div>
            <br />
            @if(Convert.ToString(ViewData["rolename"]) == "SuperUser")
            {
                <div class="row">
                    <div class="col-md-3">
                        <dt>
                            @Html.DisplayNameFor(model => model.CreatedBy)
                        </dt>
                        <dd>
                            @ViewData["creatorby"]
                        </dd>
                    </div>
                    <div class="col-md-3">
                        <dt>
                            @Html.DisplayNameFor(model => model.DateCreated)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.DateCreated)
                        </dd>
                    </div>
                    <div class="col-md-3">
                        <dt>
                            Modified By
                        </dt>
                        <dd>
                            @ViewData["modifiedby"]
                        </dd>
                    </div>
                    <div class="col-md-3">
                        <dt>
                            Date Modified
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.DateLastModified)
                        </dd>
                    </div>
                </div>
            }
        </div>

        <!--MODAL FOOTER-->
        <div class="modal-footer">
            <div class="row pull-right">
                <div class="col-md-12">
                    <a class="btn btn-danger" data-dismiss="modal">Cancel</a>
                </div>
            </div>
        </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

ImouRentACar/Views/State/Edit.cshtml
@model ImouRentACar.Models.State

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3> <strong> EDIT STATE </strong> </h3>
</div>

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="StateId" />
    <input type="hidden" asp-for="CreatedBy" />
    <input type="hidden" asp-for="DateCreated" />
    <!--MODAL BODY-->
    <div class="modal-body">
        <div class="form-horizontal">
            <div class="row">
                <div class="col-md-12">
                    <label>NAME</label>
                    <input asp-for="Name" class="form-control " placeholder="Name"/>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
        </div>
    </div>

    <!--MODAL FOOTER-->
    <div class="modal-footer">
        <div class="row pull-right">
            <div class="col-md-12">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-danger" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ImouRentACar/Views/State/Index.cshtml
@model IEnumerable<ImouRentACar.Models.State>
@using ImouRentACar.Models.Enums;

    @{
        ViewData["Title"] = "Index";
        Layout = "~/Views/Shared/AdminLayout/_AdminLayout.cshtml";
        var x = 1;
    }

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            State
        </h1>
        <ol class="breadcrumb" style="padding-bottom: 10px">
            <li><a asp-controller="Admin" asp-action="Dashboard"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active">State</li>
        </ol>


    </section>

    <!-- Main content -->
    <section class="content">
        @if (TempData["state"] != null)
        {
            if (TempData["notificationType"].Equals(NotificationType.Success.ToString()))
            {
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    @TempData["state"]
                </div>
            }
            else if (TempData["notificationtype"].Equals(NotificationType.Error.ToString()))
            {
                <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    @TempData["state"]
                </div>
            }
            else if (TempData["notificationtype"].Equals(NotificationType.Info.ToString()))
            {
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    @TempData["state"]
                </div>
            }

        }
        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <a asp-action="Create" data-modal="" class="btn btn-primary btn pull-right"><i style="color: red;" class="fa fa-plus"></i> ADD</a>
            </div>
            <div class="box-body">
                <table class="table" id="myTable">
                    <thead>
                        <tr>
                            <th>
                                S/N
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @(x++)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    <a class="btn btn-success btn-sm" asp-action="ViewLgas" asp-route-id="@item.StateId"><i class="fa fa-check "></i> View LGA</a>
                                    <a class="btn btn-info btn-sm" data-modal="" asp-action="Details" asp-route-id="@item.StateId"><i class="fa fa-book "></i> Details</a>
                                    <a class="btn btn-warning btn-sm" data-modal="" asp-action="Edit" asp-route-id="@item.StateId"><i class="fa fa-pencil-square-o "></i> Edit</a>
                                    <a class="btn btn-danger btn-sm" data-modal="" asp-action="Delete" asp-route-id="@item.StateId"><i class="fa fa-trash-o "></i> Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->

    <script src="~/Admin/bower_components/jquery/dist/jquery.js"></script>
    <script src="~/Modal/Modal.js"></script>

    <!-- modal placeholder-->
    <div id='myModal' class='modal fade in'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div id='myModalContent'>
                </div>
            </div>
        </div>
    </div>

    <script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            columnDefs: [
                {
                    targets: [0, 1, 2],
                    className: 'dataTable'
                }
            ]
        });
    });
    </script>

ImouRentACar/Views/State/ViewLgas.cshtml
@model IEnumerable<ImouRentACar.Models.LGA>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/AdminLayout/_AdminLayout.cshtml";
    var x = 1;
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        State
    </h1>
    <ol class="breadcrumb" style="padding-bottom: 10px">
        <li><a asp-controller="Admin" asp-action="Dashboard"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a asp-controller="State" asp-action="Index"> States</a></li>
        <li class="active">@ViewData["state"] LGAs</li>
    </ol>


</section>

<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">
        <div class="box-body">
            <table class="table" id="myTable">
                <thead>
                    <tr>
                        <th>
                            S/N
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @(x++)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <!-- /.box -->
</section>
<!-- /.content -->

<script src="~/Admin/bower_components/jquery/dist/jquery.js"></script>
<script src="~/Modal/Modal.js"></script>

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            columnDefs: [
                {
                    targets: [0, 1, 2],
                    className: 'dataTable'
                }
            ]
        });
    });
</script>>