ImouRentACar/Models/CarBrand.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ImouRentACar.Models
{
    public class CarBrand : Transport
    {
        #region Data Model

        public int CarBrandId { get; set; }

        public string Name { get; set; }

        #endregion
    }
}

ImouRentACar/Controllers/CarBrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ImouRentACar.Data;
using ImouRentACar.Models;
using ImouRentACar.Models.Enums;
using ImouRentACar.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace ImouRentACar.Controllers
{
    public class CarBrandController : Controller
    {
        private readonly ApplicationDbContext _database;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private ISession _session => _httpContextAccessor.HttpContext.Session;

        #region Constructor

        public CarBrandController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _database = context;
            _httpContextAccessor = httpContextAccessor;
        }

        #endregion

        #region Index

        [SessionExpireFilterAttribute]
        [Route("carbrand/index")]
        public async Task<IActionResult> Index()
        {
            var userid = _session.GetInt32("imouloggedinuserid");
            var _user = await _database.ApplicationUsers.FindAsync(userid);
            ViewData["loggedinuserfullname"] = _user.DisplayName;

            var roleid = _user.RoleId;

            var role = _database.Roles.Find(roleid);

            ViewData["userrole"] = role.Name;

            if (role.CanManageCars == false && role.CanDoEverything == false)
            {
                return RedirectToAction("Index", "Error");
            }

            ViewData["canmangecars"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageCars == true && r.RoleId == roleid);
            ViewData["canmangecustomers"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageCustomers == true && r.RoleId == roleid);
            ViewData["canmangelandingdetails"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageLandingDetails == true && r.RoleId == roleid);
            ViewData["canmangeprices"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManagePrices == true && r.RoleId == roleid);
            ViewData["canmangeenquries"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageEnquires == true && r.RoleId == roleid);
            ViewData["canmangebookings"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageBookings == true && r.RoleId == roleid);
            ViewData["canmangelocation"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageLocation == true && r.RoleId == roleid);
            ViewData["canmangedrivers"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageDrivers == true && r.RoleId == roleid);
            ViewData["canmangepassengersinformation"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManagePassengersInformation == true && r.RoleId == roleid);
            ViewData["candoeverything"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanDoEverything == true && r.RoleId == roleid);
            ViewData["canmanageapplicationusers"] = await _database.Roles.SingleOrDefaultAsync(r => r.CanManageApplicationUsers == true && r.RoleId == roleid);

            var brands = await _database.CarBrands.ToListAsync();

            return View(brands);
        }

        #endregion

        #region Create

        [HttpGet]
        public IActionResult Create()
        {
            var userObject = _session.GetString("imouloggedinuser");
            var _user = JsonConvert.DeserializeObject<ApplicationUser>(userObject);
            var roleid = _user.RoleId;
            var role = _database.Roles.Find(roleid);
            if (role.CanManageCars == false && role.CanDoEverything == false)
            {
                return RedirectToAction("Index", "Error");
            }

            var brand = new CarBrand();
            return PartialView("Create", brand);
        }

        [HttpPost]
        [SessionExpireFilterAttribute]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CarBrand brand)
        {
            if (ModelState.IsValid)
            {
                var allBrands = await _database.CarBrands.ToListAsync();
                if (allBrands.Any(b => b.Name == brand.Name))
                {
                    TempData["carbrand"] = "You cannot add " + brand.Name + " car brand because it already exist!!!";
                    TempData["notificationType"] = NotificationType.Error.ToString();
                    return View("Index");
                }
                
                var _brand = new CarBrand()
                {
                    Name = brand.Name,
                    CreatedBy = Convert.ToInt32(_session.GetInt32("imouloggedinuserid")),
                    DateCreated = DateTime.Now,
                    LastModifiedBy = Convert.ToInt32(_session.GetInt32("imouloggedinuserid")),
                    DateLastModified = DateTime.Now
                };

                await _database.CarBrands.AddAsync(_brand);
                await _database.SaveChangesAsync();

                TempData["carbrand"] = "You have successfully added " + brand.Name + " car brand.";
                TempData["notificationType"] = NotificationType.Success.ToString();

                return Json(new { success = true });
            }

            return View("Index");
        }

        #endregion

        #region Edit

        [HttpGet]
        [SessionExpireFilterAttribute]
        public async Task<IActionResult> Edit(int? id)
        {
            var userObject = _session.GetString("imouloggedinuser");
            var _user = JsonConvert.DeserializeObject<ApplicationUser>(userObject);
            var roleid = _user.RoleId;
            var role = _database.Roles.Find(roleid);
            if (role.CanManageCars == false && role.CanDoEverything == false)
            {
                return RedirectToAction("Index", "Error");
            }

            if (id == null)
            {
                return RedirectToAction("Index", "Error");
            }

            var _brand = await _database.CarBrands.SingleOrDefaultAsync(b => b.CarBrandId == id);

            if (_brand == null)
            {
                return RedirectToAction("Index", "Error");
            }

            return PartialView("Edit", _brand);
        }
        
        [HttpPost]
        [SessionExpireFilterAttribute]
        public async Task<IActionResult> Edit(int id, CarBrand brand)
        {
            if(id != brand.CarBrandId)
            {
                return RedirectToAction("Index", "Error");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    brand.LastModifiedBy = Convert.ToInt32(_session.GetInt32("imouloggedinuserid"));
                    brand.DateLastModified = DateTime.Now;
                    _database.Update(brand);
                    await _database.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarBrandExists(brand.CarBrandId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                TempData["carbrand"] = "You have successfully modified " + brand.Name + " car brand.";
                TempData["notificationType"] = NotificationType.Success.ToString();

                return Json(new { success = true });
            }
            return View(brand);
        }

        #endregion

        #region Delete

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            var userObject = _session.GetString("imouloggedinuser");
            var _user = JsonConvert.DeserializeObject<ApplicationUser>(userObject);
            var roleid = _user.RoleId;
            var role = _database.Roles.Find(roleid);
            if (role.CanManageCars == false && role.CanDoEverything == false)
            {
                return RedirectToAction("Index", "Error");
            }

            if ( id == null)
            {
                return RedirectToAction("Index", "Error");
            }

            var brand = await _database.CarBrands.SingleOrDefaultAsync(b => b.CarBrandId == id);

            if(brand == null)
            {
                return RedirectToAction("Index", "Error");
            }
            
            return PartialView("Delete", brand);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var brand = await _database.CarBrands.SingleOrDefaultAsync(b => b.CarBrandId == id);

            if (brand != null)
            {
                _database.CarBrands.Remove(brand);
                await _database.SaveChangesAsync();

                TempData["carbrand"] = "You have successfully deleted  " + brand.Name + "  car brand!!!";
                TempData["notificationType"] = NotificationType.Success.ToString();

                return Json(new { success = true });
            }
            return View("Index");
        }

        #endregion

        #region View Cars

        [HttpGet]
        [Route("carbrand/viewcars")]
        public async Task<IActionResult> ViewCars(int? id)
        {
            var userObject = _session.GetString("imouloggedinuser");
            var _user = JsonConvert.DeserializeObject<ApplicationUser>(userObject);
            var roleid = _user.RoleId;
            var role = _database.Roles.Find(roleid);
            if (role.CanManageCars == false && role.CanDoEverything == false)
            {
                return RedirectToAction("Index", "Error");
            }

            ViewData["userrole"] = role.Name;

            if (id == null)
            {
                return RedirectToAction("Index", "Error");
            }
            

ImouRentACar/Views/CarBrand/Create.cshtml
@model ImouRentACar.Models.CarBrand

@{
    ViewData["Title"] = "Create";
    Layout = null;
}

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3> <strong> ADD CAR BRAND </strong> </h3>
</div>

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <!--MODAL BODY-->
    <div class="modal-body">
        <div class="form-horizontal">
            <div class="row">
                <div class="col-md-12">
                    <label>NAME</label>
                    <input asp-for="Name" class="form-control" placeholder="Name" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
        </div>
    </div>

    <!--MODAL FOOTER-->
    <div class="modal-footer">
        <div class="row pull-right">
            <div class="col-md-12">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a class="btn btn-danger" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ImouRentACar/Views/CarBrand/Delete.cshtml
@model ImouRentACar.Models.CarBrand

@{ 
    ViewData["Title"] = "Delete";
    Layout = null;
}

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3> <strong> DELETE CAR BRAND </strong> </h3>
</div>


<!--MODAL BODY-->
<div class="modal-body">
    <h3 class="text-center"> Are you sure you want to delete @Html.DisplayFor(model => model.Name) Car Brand?</h3>
</div>
<form asp-action="Delete">
    <input type="hidden" asp-for="CarBrandId" />

    <!--MODAL FOOTER-->
    <div class="modal-footer">
        <div class="row pull-right">
            <div class="col-md-12">
                <input type="submit" value="Yes" class="btn btn-primary" />
                <a class="btn btn-danger" data-dismiss="modal">No</a>
            </div>
        </div>
    </div>
</form>

ImouRentACar/Views/CarBrand/Edit.cshtml
@model ImouRentACar.Models.CarBrand

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3> <strong> EDIT CAR BRAND </strong> </h3>
</div>

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="CarBrandId" />
    <input type="hidden" asp-for="CreatedBy"/>
    <input type="hidden" asp-for="DateCreated"/>
    <!--MODAL BODY-->
    <div class="modal-body">
        <div class="form-horizontal">
            <div class="row">
                <div class="control-label col-md-2">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control " />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
        </div>
    </div>

    <!--MODAL FOOTER-->
    <div class="modal-footer">
        <div class="row pull-right">
            <div class="col-md-12">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-danger" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ImouRentACar/Views/CarBrand/Index.cshtml
@model IEnumerable<ImouRentACar.Models.CarBrand>
@using ImouRentACar.Models.Enums

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/AdminLayout/_AdminLayout.cshtml";
    var x = 1;
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        CAR BRAND
    </h1>
    <ol class="breadcrumb" style="padding-bottom: 10px">
        <li><a asp-controller="Admin" asp-action="Dashboard"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active">Car Brand</li>
    </ol>


</section>

<!-- Main content -->
<section class="content">
    @if (TempData["carbrand"] != null)
    {
        if (TempData["notificationType"].Equals(NotificationType.Success.ToString()))
        {
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                @TempData["carbrand"]
            </div>
        }
        else if (TempData["notificationtype"].Equals(NotificationType.Error.ToString()))
        {
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                @TempData["carbrand"]
            </div>
        }
        else if (TempData["notificationtype"].Equals(NotificationType.Info.ToString()))
        {
            <div class="alert alert-info alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                @TempData["carbrand"]
            </div>
        }

    }
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <a asp-action="Create" data-modal="" class="btn btn-primary btn pull-right"><i style="color: red;" class="fa fa-plus"></i> ADD</a>
        </div>
        <div class="box-body">
            <table class="table" id="myTable">
                <thead>
                    <tr>
                        <th>
                            S/N
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @(x++)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                <a class="btn btn-success btn-sm" asp-action="ViewCars" asp-route-id="@item.CarBrandId"><i class="fa fa-check "></i> View Cars</a>
                                <a class="btn btn-warning btn-sm" data-modal="" asp-action="Edit" asp-route-id="@item.CarBrandId"><i class="fa fa-pencil-square-o "></i> Edit</a>
                                <a class="btn btn-danger btn-sm" data-modal="" asp-action="Delete" asp-route-id="@item.CarBrandId"><i class="fa fa-trash-o "></i> Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <!-- /.box -->
</section>
<!-- /.content -->

<script src="~/Admin/bower_components/jquery/dist/jquery.js"></script>
<script src="~/Modal/Modal.js"></script>

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            columnDefs: [
                {
                    targets: [0, 1, 2],
                    className: 'dataTable'
                }
            ]
        });
    });
</script>

ImouRentACar/Views/CarBrand/ViewCars.cshtml
@model IEnumerable<ImouRentACar.Models.Car>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/AdminLayout/_AdminLayout.cshtml";
    var x = 1;
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1 style="text-transform: capitalize">
        CARS
    </h1>
    <ol class="breadcrumb" style="padding-bottom: 10px">
        <li><a asp-controller="Admin" asp-action="Dashboard"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a asp-controller="CarBrand" asp-action="Index">Car Brand</a></li>
        <li class="active">All Cars In @ViewData["brandname"]</li>
    </ol>


</section>

<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3>
                Car Brand: @ViewData["brandname"]

                <a asp-action="Index" asp-controller="CarBrand" class="btn btn-primary btn pull-right"><i style="color: red;" class="fa fa-arrow-left"></i> Go Back</a>
            </h3>
            
        </div>
        <div class="box-body">
            <table class="table" id="myTable">
                <thead>
                    <tr>
                        <th>
                            S/N
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>

                        <th>
                            Description
                        </th>
                        <th>
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @(x++)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                <a class="btn btn-info btn-sm" data-modal="" asp-action="Details" asp-controller="Car" asp-route-id="@item.CarId"><i class="fa fa-book "></i> Details</a>
                                <a class="btn btn-success btn-sm" data-modal="" asp-action="ViewImage" asp-controller="Car" asp-route-id="@item.CarId"><i class="fa fa-picture-o "></i> View Image</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <!-- /.box -->
</section>
<!-- /.content -->

<script src="~/Admin/bower_components/jquery/dist/jquery.js"></script>
<script src="~/Modal/Modal.js"></script>

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            columnDefs: [
                {
                    targets: [0, 1, 2],
                    className: 'dataTable'
                }
            ]
        });
    });
</script>